package com.namami.domain.types;

public enum AgreementTrackerStatus {

	
	AGREEMENT_TERMS_ADDED 	(1), //DATA_INPUT_IN_PROGRESS (1)
		
	AGREEMENT_OWNER_ADDED (2), //DATA_INPUT_IN_PROGRESS (1)
	
	AGREEMENT_TENENT_ADDED (3), //DATA_INPUT_IN_PROGRESS (1)
		
	AGREEMENT_WITNESS_ADDED (4), //DATA_INPUT_IN_PROGRESS (1)
	
	AGREEMENT_PROPERTY_ADDED (5),//DATA_INPUT_IN_PROGRESS (1)
	
	AGREEMENT_MISCE_ADDED (6),//DATA_INPUT_IN_PROGRESS (1)
	
	AGREEMENT_ALL_REQ_DATA_ADDED (7), //DATA_INPUT_DONE (2),
	
	USR_PYMENT_DONE (8),//PAYMENT_DONE (3),
	
	ASSOCIATE_ASSIGNED (9), //PAYMENT_DONE (3),
	
	// from 10 to 30 updated by associate for now
	
	USR_DRAFT_GENERATED (10),//DRAFT_COPY_GENERATED (4),
	
	USR_DRAFT_SENT_FOR_APPROVAL (11), //DRAFT_COPY_GENERATED (4),
	
	DRAFT_APPROVED_BY_OWNER (12), //DRAFT_APPROVED (5),
	
	DRAFT_APPROVED_BY_TENENT (13), //DRAFT_APPROVED (5),
	
	DRAFT_REJECTED_BY_OWNER (33), //MODIFICATION_IN_PROGRESS (15),
	
	DRAFT_REJECTED_BY_TENENT (34), //MODIFICATION_IN_PROGRESS (15),
	
	DRAFT_MODIFICATION_REQ_BY_PERSONS(14),//MODIFICATION_IN_PROGRESS (15),
	
	DRAFT_MODIFICATION_IN_PROGRESS (15),//MODIFICATION_IN_PROGRESS (15),
	
	DRAFT_MODIFICATION_DONE (16),//DRAFT_APPROVED (5),
	
	OWNER_BIOMETRIC_IN_PROGRESS (17),//BIOMETRIC_IN_PROGRESS (6),
	
	OWNER_BIOMETRIC_IN_DONE (18),//BIOMETRIC_IN_PROGRESS (6),
	
	TENENT_BIOMETRIC_IN_PROGRESS (19),//BIOMETRIC_IN_PROGRESS (6),
	
	TENENT_BIOMETRIC_IN_DONE (20),//BIOMETRIC_IN_PROGRESS (6),
	
	WITNESS_BIOMETRIC_IN_PROGRESS (21),//BIOMETRIC_IN_PROGRESS (6),
	
	WITNESS_BIOMETRIC_DONE (22),//BIOMETRIC_IN_PROGRESS (6),
	
	BIOMETRIC_DONE (23),//BIOMETRIC_DONE (7),
	
	CHALAN_CREATED (24),//GOVERNMENT_PROCESS_IN_PROGRESS(8),
	
	GOVT_DRAFT_CREATED (25),//GOVERNMENT_PROCESS_IN_PROGRESS(8),
	
	GOVT_DRAFT_SUBMITTED(26),//GOVERNMENT_PROCESS_IN_PROGRESS(8),
	
	GOVT_LNL_APPROVED(27),//GOVERNMENT_PROCESS_DONE(8),
	
	HARD_COPY_DISPATCHED_IN_PROGRESS (28),//GOVERNMENT_PROCESS_DONE(8),
	
	HARD_COPY_DISPATCHED_TO_USER (29),//HARD_COPY_DISPATCHED (13),
	
	COMPLETED (30),//COMPLETED (14),
	
	AGREEMENT_DATA_DELETED (31),//DATA_INPUT_IN_PROGRESS (1)
	
	AGREEMENT_DATA_UPDATED (32),//DATA_INPUT_IN_PROGRESS (1)
	;
	
	
	
	private final Integer value;
	
	AgreementTrackerStatus(Integer agreementStatus) {
		this.value = agreementStatus;
	}

	public Integer getValue() {
		return value;
	}
	
}
